config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  resources :moves

end

app/models/instruction.rb
class Instruction < ActiveRecord::Base
	belongs_to :move

	def parser(string)

	end
end

app/models/move.rb
class Move < ActiveRecord::Base
	has_one :instruction
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/moves_controller.rb
class MovesController < ApplicationController

	def index
	end

	def show
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/moves_helper.rb
module MovesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DO</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/moves/index.html.erb
<h1> Hello moves </h1>

<h1><%= params[:anatomy] %></h1>

<% Move.where(anatomy: params[:anatomy]).each do |move| %>
<p> <%= link_to move.title, move_path(move) %> </p>
<% end %>

app/views/moves/show.html.erb
<% move = Move.find_by(params[:id]) %>

<h1> <%= move.title %> </h1>

<p> <%= move.instruction.text %> </p>

app/views/welcome/index.html.erb
<h1>Welcome </h1>

<%= link_to("Cervical",moves_path(anatomy: "cervical"))%>
<%= link_to("Thoracic",moves_path(anatomy: "thoracic"))%>
<%= link_to("Lumbar",moves_path(anatomy: "lumbar"))%>